#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-style:
    runs-on: ubuntu-18.04
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - uses: actions-rs/toolchain@b223206e28798aa3c3668bdd6409258e6dc29172
      with:
        toolchain: nightly-2020-07-26
        default: false
        components: rustfmt
    - name: Check style
      run: cargo +nightly-2020-07-26 fmt -- --check

  clippy-lint:
    runs-on: ubuntu-18.04
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - name: Run Clippy Lints
      run: cargo clippy -- -D warnings

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-2019, macos-10.15 ]
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - uses: actions-rs/toolchain@b223206e28798aa3c3668bdd6409258e6dc29172
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose

  build-and-test-illumos:
    runs-on: ubuntu-latest
    steps:
    - uses: jclulow/action-agogo@main
      with:
        secret: ${{ secrets.BUILDOMAT_SECRET }}
        baseurl: https://sys.illumos.org/buildomat
        script: |
          uname -a

          echo "::group::git show"
          git show
          echo "::endgroup::"

          echo "::group::install tools"
          pkg install git build-essential
          echo "::endgroup::"

          echo "::group::install rust stable toolchain"
          export RUSTUP_HOME=/rustup
          export CARGO_HOME=/rustup
          export PATH="$CARGO_HOME/bin:$PATH"
          curl -sSf https://sh.rustup.rs | bash -s -- \
              -y \
              --default-toolchain stable \
              --no-modify-path
          echo "::endgroup::"

          echo "::group::environment variable dump"
          env
          echo "::endgroup::"

          banner build
          cargo build --tests --verbose

          banner test
          cargo test --verbose
